### PR TITLE
Made a whole bunch of changes to the files and directory structure.  …

### PR DESCRIPTION
**Pull request by jimmyo15**
…Going to have to update the nohup command to point to the new location of the streamer in the views.py file.  Take a look.  This pull request will merge the changes back to development, which is where I pulled them from.  We shouldn't merge to master just yet in case the app breaks somewhere unexpectedly as a result of this.  I tried to break it out with a directory that summarizes what each piece is doing, tweet ingestion, financials, analysis, test, webserver.  I created a ui directory so we can decouple ui code from the webserver at a later date, too.

### CODE REVIEW

**Comment by MSnowman** [comment]
Like the idea behind this but think we need to make some adjustments

** webserver folder rename from app**
1. If you want to change the name from "app" I think flask_app is more appropriate as that is the only info in my view that should go in here.
- simplewebserver.py
  - What does this do?  Does it really belong in the flask app?

**financialsIngestion folder**
Thinking we leave all APIs where we get data in the API folder.   This way if/when we start looking for other sources it is all in one folder.  Think we can delete this folder
 
**db Folder**
Don't think this is the appropriate name, too vaugh.  Thought Pipeline was a good name because it should contain all the services used to pipe data from one db/location to another

**Comment by MSnowman** [comment]
Good work cleaning a ton of stuff up though!

**Comment by jimmyo15** [comment]
This is good discussion.  Will help us to speak same language around naming.

webserver rename from app - can rename to flask_app, that makes sense to
me.  Will drop the simple webserver item.  Honestly not sure why that was
in there anyway but wanted to err on the side of caution with deleting.

financialsIngestion vs API - When thinking about our code, or code
libraries in general, when I see an API directory I think it is an API to
access the functionality that is being exposed by that code.  So when I
think API in terms of our work I think of it in the sense of if we created
an API to access what we have built so others can use it.  Any time we are
accessing another API we are doing it for some purpose that we need, so was
trying to be more descriptive about what we are building in the directory
name.

db vs. pipeline - I see what you are saying.  Is there a different term we
can use?  When I think pipeline I think of the entire data flow to some
destination, not necessarily just mongodb to sql.

Let's have a quick chat to agree on naming.

**Comment by MSnowman** [comment]
Hey 

webserver to flask_app - cool like it. 

API - gotcha. I views it the opposite (external) but I get your point now.  How about IngestionAPIs?

DB vs. pipeline
Micro_connections or something along those lines. All about weaving the separate smaller apps together.

**Pull request merged**
